### ISSUE TITLE
Need option to only populate if data doesn't already exist in collection

### ISSUE THREAD

**Issue by tigerclaw-az** [bellstrand/mongoose-seed-db#2]
I noticed that I can use `clearAll()` to clear the data in the given model(s) before it populates the data, but I would like an option that would allow it not to populate if there is already data if I don't use the `clearAll()`.

Example:
```
mongooseSeed.loadModels(...);
mongooseSeed.populate(...); // Don't populate if data exists
```

I recognize that I could just do a `find()` on the model that I don't want to populate and then not even call the `populate()` function, but if I have many different models, then I would like the library to handle this for each one.

I'm thinking you could make it another property in the object that gets sent through the population? This way it would be granular enough to allow only certain models to not populate.

**Comment by bellstrand** [comment]
Hmm, that would be neat yes.
I'll have to rewrite some of the code in the populate function in order to make this happen.
Will see when I can squeeze in some time for it.

**Comment by bellstrand** [comment]
@ejwaibel I've implemented what you asked for in 0.0.9.
Try calling:
mongooseSeed.populate(path, { populateExisting: false });
after loading the models etc ofc, and it will check if the collections has entries and if they do it will not populate them.

Try it out and get back to me, on Friday I'll leave for a 2 week vacation, so if you respond after that then you know why it'll take me some time to respond.

**Comment by tigerclaw-az** [comment]
Bingo! Thank you @bellstrand for working so quickly and following my crazy demands ;)

The only issue I found was that I needed to install `babel-polyfill` and put `require('babel-polyfill')` at the top of your file. Otherwise I was getting the error: `mongodb connection error regeneratorRuntime is not defined`

**Comment by bellstrand** [comment]
Ah, I had no need to polyfill that in my environment.
And we need that dependency because I rewrote some code to use async/await to make it a bit cleaner.
I've added it as a dependency so you don't need to require it now with 0.0.10

**Comment by bellstrand** [comment]
@ejwaibel Can I close this issue now?

**Comment by tigerclaw-az** [comment]
@bellstrand yes, sorry for the delay, didn't see your message come through my inbox. thanks again!
